parameters:
    bm_breadcrumb.manager.class: BCM\BreadcrumbBundle\Service\BreadcrumbManager

services:
    bm_breadcrumb.manager:
        class: %bm_breadcrumb.manager.class%
        arguments: [@request, @router, @templating]
        scope: request
