parameters:
    bcm_breadcrumb.manager.class: BCM\BreadcrumbBundle\Service\BreadcrumbManager

services:
    bcm_breadcrumb.manager:
        class: %bcm_breadcrumb.manager.class%
        arguments: [@request, @router, @templating]
        scope: request